# Generated by Django 5.0.3 on 2024-03-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.CharField(max_length=2084, unique=True)),
                ('short_url', models.CharField(max_length=100)),
                ('clicks', models.IntegerField(default=0)),
            ],
        ),
    ]
