# Generated by Django 5.0.3 on 2024-03-24 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relay', '0002_alter_url_options_alter_url_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='url',
            managers=[
            ],
        ),
    ]
