# Generated by Django 5.0.3 on 2024-03-24 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relay', '0003_alter_url_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url',
            options={'ordering': ('-visits',)},
        ),
        migrations.RenameField(
            model_name='url',
            old_name='short_url',
            new_name='short',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='long_url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='clicks',
            new_name='visits',
        ),
    ]
